<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UnitsProfileSeeder extends Seeder
{
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        $list = $this->descriptions();
        foreach ($list as $code => $description) {
            $unit = $this->db->table('master_service_units')
                ->select('id')->where('code', $code)->get()->getRow();
            if (! $unit) continue;
            $exists = $this->db->table('units_profiles')
                ->where('service_unit_id', $unit->id)->get()->getRow();
            if ($exists) {
                $this->db->table('units_profiles')->where('id', $exists->id)
                    ->update(['description' => trim($description), 'is_active' => 1, 'updated_at' => $now]);
            } else {
                $this->db->table('units_profiles')->insert([
                    'service_unit_id' => $unit->id,
                    'description' => trim($description),
                    'is_active' => 1, 'created_at' => $now, 'updated_at' => $now,
                ]);
            }
        }
    }

    private function descriptions(): array
    {
        return [
            'ULT' => 'Unit Layanan Terpadu (ULT) adalah pintu utama pelayanan administrasi terpadu Politeknik Negeri Bandung (POLBAN). ULT menerima, memverifikasi berkas, meneruskan pengajuan ke unit tujuan, dan memantau status tiket sampai selesai. Seluruh pengajuan mahasiswa, dosen, tendik, alumni, dan umum wajib masuk via ULT tatap muka atau SI-ULT daring. Cakupannya: akademik, keuangan, kemahasiswaan, perpustakaan, kepegawaian, TI, dan administrasi umum. ULT tidak memutus keputusan akhir, melainkan menjamin pengajuan diteruskan ke unit berwenang dengan status jelas: diterima, diproses, selesai, atau ditolak beserta alasan. Setiap pengajuan bertiket dengan nomor tracking mandiri. Tatap muka Senin-Jumat 08.00-16.00 WIB di kampus Gegerkalong Hilir, Ciwaruga, Parongpong, Bandung Barat. Daring 24 jam, diverifikasi jam kerja. Bawa identitas (KTM/KTP/NIP) dan dokumen pendukung sesuai syarat.',
            'AKD' => 'Bagian Akademik bertanggung jawab atas seluruh administrasi akademik mahasiswa POLBAN: penerimaan mahasiswa baru, registrasi/heregistrasi, KRS, nilai dan transkrip, surat keterangan akademik, hingga kelulusan dan wisuda. Layanan utamanya meliputi surat keterangan aktif kuliah, keterangan lulus sementara, legalisasi ijazah/transkrip, perbaikan data akademik, layanan cuti dan pengunduran diri, perpindahan program studi, serta administrasi ujian tugas akhir, yudisium, dan wisuda. Pengajuan via ULT diverifikasi kelengkapan berkasnya lalu diteruskan ke Bagian Akademik. Pemohon wajib memastikan NIM, nama, prodi, dan angkatan benar serta melampirkan KTM, KHS terakhir, atau surat pengantar jurusan bila dipersyaratkan. Layanan tatap muka Senin-Jumat jam kerja; pengajuan daring via SI-ULT diproses pada jam kerja. Untuk keperluan mendesak (lamaran/beasiswa), cantumkan kebutuhan pada catatan agar diprioritaskan.',
            'KEU' => 'Bagian Keuangan mengelola administrasi keuangan mahasiswa dan layanan keuangan POLBAN: penetapan dan penagihan UKT, penerimaan pembayaran, penerbitan bukti bayar dan surat bebas tunggakan, penyaluran dana beasiswa, serta rekonsiliasi dengan bank mitra. Layanannya meliputi informasi tagihan dan cara bayar UKT/SPP, cetak ulang kuitansi, surat lunas/bebas tunggakan untuk syarat yudisium/wisuda/pengambilan ijazah, keringanan atau penundaan UKT, refund kelebihan bayar, dan konfirmasi pembayaran yang belum terbaca sistem. Pengajuan via ULT diteruskan ke Bagian Keuangan beserta bukti transfer, NIM, semester, dan nomor VA. Wajib memakai VA resmi atas nama mahasiswa dan menyimpan bukti sampai status lunas. Bila sudah bayar namun masih menunggak, ajukan tiket konfirmasi dengan bukti jelas (pengirim, tanggal, nominal, VA tujuan). Keringanan UKT hanya pada periode resmi dengan surat permohonan, slip penghasilan ortu/wali, KK, dan dokumen pendukung ekonomi.',
            'KEMHS' => 'Bagian Kemahasiswaan membina dan melayani kegiatan kemahasiswaan POLBAN: penalaran, minat-bakat, kesejahteraan mahasiswa, Ormawa, serta pembinaan karakter dan disiplin. Layanannya meliputi surat rekomendasi dan surat tugas kegiatan, legalisasi sertifikat, pendataan prestasi regional/nasional/internasional, bantuan dana kegiatan Ormawa, konseling dan pembinaan, administrasi beasiswa prestasi/afirmasi sisi kemahasiswaan, serta SKPI kegiatan kokurikuler. Pengajuan beasiswa umum, dispensasi, dan izin lomba dikoordinasikan unit ini. Pengajuan via ULT diteruskan untuk verifikasi dan persetujuan. Untuk dana kegiatan atau rekomendasi lomba, lampirkan proposal lengkap (latar belakang, panitia/peserta, RAB, jadwal, persetujuan pembina/jurusan). Dispensasi kuliah wajib melampirkan surat tugas dan jadwal. Layanan tatap muka jam kerja; daring via SI-ULT diproses jam kerja.',
            'PERPUS' => 'Perpustakaan POLBAN menyediakan sumber belajar dan referensi ilmiah: buku teks, e-journal, prosiding, tugas akhir/skripsi, serta koleksi digital via e-library, plus ruang baca, ruang diskusi, komputer, dan internet. Layanannya: keanggotaan dan perpanjangan, peminjaman-pengembalian, referensi dan penelusuran literatur, literasi informasi, surat bebas pustaka untuk syarat yudisium/wisuda/pengambilan ijazah, dan unggah karya ilmiah ke repositori. Denda keterlambatan berlaku dan wajib lunas sebelum bebas pustaka terbit. Untuk bebas pustaka pastikan tidak ada pinjaman dan denda; cantumkan NIM, nama, prodi, dan keperluan. Pinjam buku wajib kartu anggota/KTM berlaku. Ruang baca mengikuti jam kerja (diperpanjang saat ujian); perpanjangan dan cek katalog daring kapan saja via portal.',
            'JUR' => 'Jurusan adalah pelaksana akademik vokasi POLBAN: mengatur perkuliahan, bimbingan akademik dan tugas akhir, penilaian, lab/bengkel, serta pembinaan dosen-mahasiswa. Layanannya: surat pengantar dan rekomendasi (penelitian, KP, magang), surat pembimbing TA, penjadwalan seminar proposal dan sidang TA, surat izin penelitian/pengambilan data, legalisasi tingkat jurusan, dan pengaduan akademik. Banyak pengajuan ke Akademik/ULT mensyaratkan pengantar atau persetujuan jurusan/prodi asal. Koordinasikan dulu dengan dosen wali atau koordinator prodi; cantumkan NIM, prodi, semester, pembimbing (bila TA), maksud dan tujuan. Pengantar penelitian/magang wajib melampirkan proposal atau surat penerimaan instansi. Jam layanan mengikuti jam kerja dan jadwal kuliah/praktikum tiap jurusan.',
            'UPTIK' => 'UPT Teknologi Informasi dan Komunikasi (UPT TIK) mengelola infrastruktur dan layanan TI POLBAN: jaringan internet, sistem informasi akademik dan pendukung, surel resmi, akun sivitas, keamanan sistem, dan dukungan teknis aplikasi. Layanannya: pembuatan dan reset akun (portal akademik, surel kampus, SI-ULT), perbaikan gagal login, jaringan dan WiFi kampus, pendampingan pemakaian sistem bagi dosen/tendik/mahasiswa, dan penanganan insiden keamanan akun. Laporan via tiket ULT diteruskan ke UPT TIK beserta data teknis: NIM/NIP, surel terdampak, screenshot galat, waktu kejadian, dan perangkat. Sampaikan kronologi rinci dan jangan membagikan kata sandi ke siapa pun; reset hanya setelah verifikasi identitas pemilik. Helpdesk Senin-Jumat jam kerja; lapor via SI-ULT 24 jam dan ditindaklanjuti jam kerja. Penghentian layanan sementara diumumkan via kanal resmi.',
            'ADM' => 'Administrasi Umum menangani ketatausahaan dan dukungan administrasi umum sivitas POLBAN: tertib surat, dokumen dinas, arsip, dan penghubung antara pemohon dengan pimpinan dan unit terkait. Layanannya: penerimaan dan penomoran surat masuk/keluar, surat tugas dinas, surat keterangan umum, surat pengantar pimpinan, legalisasi dokumen umum, arsip dan pencarian dokumen, serta fasilitasi tanda tangan pejabat berwenang. Pengajuan via ULT diverifikasi, diberi nomor tiket, lalu diteruskan ke Administrasi Umum sesuai disposisi dan kewenangan penandatangan. Isi maksud dan tujuan surat dengan jelas, cantumkan identitas lengkap (nama, NIM/NIP, unit/prodi, kontak aktif), dan lampirkan pendukung seperti pengantar jurusan atau bukti keperluan. Waktu selesai tergantung jenis surat dan tanda tangan pejabat; surat bertanda tangan direktur/wakil membutuhkan waktu mengikuti agenda pimpinan. Daring via SI-ULT kapan saja, diproses Senin-Jumat jam kerja.',
            'BAUK' => 'Bagian Administrasi Umum dan Kepegawaian (BAUK) mengelola administrasi kepegawaian, ketatausahaan, kerumahtanggaan, dan aset POLBAN. Melayani dosen dan tendik dalam siklus kepegawaian: pengangkatan, kenaikan pangkat dan jabatan, penilaian kinerja, cuti, mutasi, sampai pensiun, dengan tertib data pada sistem resmi. Layanannya: surat keterangan pegawai aktif, pengalaman kerja, cuti (tahunan/sakit/bersalin/besar), pengantar kenaikan pangkat dan jabatan fungsional, legalisasi SK dan dokumen kepegawaian, angka kredit, kehadiran dan disiplin, serta kerumahtanggaan seperti peminjaman ruangan, kendaraan dinas, dan sarpras. Pengajuan via ULT diverifikasi lalu diteruskan ke BAUK sesuai aturan kepegawaian. Lampirkan NIP/NIDN/NUPTK, unit kerja, dan pendukung sesuai jenis layanan (misal keterangan dokter untuk cuti sakit, undangan tugas untuk surat tugas). Kenaikan pangkat/jabatan mengikuti periode dan batas berkas angka kredit. Tatap muka Senin-Jumat jam kerja; daring via SI-ULT diproses jam kerja berikutnya.',
        ];
    }
}
