<?php
namespace App\Controllers;
use App\Models\KemahasiswaanTicketModel;
class Kemahasiswaan extends BaseController
{
    private const UNIT='Kemahasiswaan'; private KemahasiswaanTicketModel $tickets;
    public function __construct(){ $this->tickets=new KemahasiswaanTicketModel(); }
    public function index(){return $this->dashboard();}
    public function dashboard(){return view('Kemahasiswaan/dashboard',$this->viewData($this->all()));}
    public function dataTiket(){ $k=trim((string)$this->request->getGet('keyword'));$q=$this->tickets->orderBy('id','DESC');if($k)$q->groupStart()->like('ticket_number',$k)->orLike('applicant_name',$k)->orLike('service_name',$k)->orLike('status',$k)->groupEnd();$r=$q->findAll();foreach($r as &$x)$x['status_tampilan']=$this->label($x['status']??'submitted');return view('Kemahasiswaan/data_tiket',['tickets'=>$r,'tiket'=>$r,'keyword'=>$k,'unit'=>self::UNIT,'nama_unit'=>self::UNIT]);}
    public function statistik(){return view('Kemahasiswaan/statistik',$this->viewData($this->all()));}
    public function logAktivitas(){ $k=trim((string)$this->request->getGet('keyword'));$q=db_connect()->table('kemahasiswaan_activity_logs al')->select('al.*,t.ticket_number AS no_tiket,t.unit_name AS unit,t.service_name AS layanan')->join('kemahasiswaan_tickets t','t.id=al.ticket_id','left')->orderBy('al.created_at','DESC');if($k)$q->groupStart()->like('al.activity',$k)->orLike('al.action',$k)->orLike('t.ticket_number',$k)->groupEnd();return view('Kemahasiswaan/log_aktivitas',['unit'=>self::UNIT,'units'=>[self::UNIT],'logs'=>$q->get()->getResultArray(),'keyword'=>$k]);}
    public function profile(){return view('Kemahasiswaan/profile',['unit'=>self::UNIT]);} public function updateProfile(){return redirect()->to(base_url('kemahasiswaan/profile'))->with('success','Profil diperbarui.');}
    public function detail($id){$t=$this->tickets->find((int)$id);if(!$t)return redirect()->back()->with('error','Tiket tidak ditemukan.');return view('Kemahasiswaan/detail',['ticket'=>$this->decorate($t),'tiket'=>$this->decorate($t),'unit'=>self::UNIT]);}
    public function proses($id){$t=$this->tickets->find((int)$id);if(!$t)return redirect()->back()->with('error','Tiket tidak ditemukan.');return view('Kemahasiswaan/proses',['ticket'=>$this->decorate($t),'tiket'=>$this->decorate($t),'unit'=>self::UNIT]);}
    public function updateProses($id){$t=$this->tickets->find((int)$id);if(!$t)return redirect()->back()->with('error','Tiket tidak ditemukan.');$in=strtolower((string)$this->request->getPost('status'));$s=['menunggu'=>'submitted','diproses'=>'processing','selesai'=>'completed','ditolak'=>'rejected'][$in]??null;if(!$s)return redirect()->back()->with('error','Status tiket tidak valid.');$this->tickets->update((int)$id,['status'=>$s,'admin_note'=>trim((string)$this->request->getPost('catatan')),'processed_at'=>$s==='processing'?date('Y-m-d H:i:s'):$t['processed_at'],'completed_at'=>$s==='completed'?date('Y-m-d H:i:s'):$t['completed_at']]);return redirect()->to(base_url('kemahasiswaan/detail/'.$id))->with('success','Status tiket diperbarui.');}
    public function upload($id){$t=$this->tickets->find((int)$id);if(!$t)return redirect()->back()->with('error','Tiket tidak ditemukan.');return view('Kemahasiswaan/upload',['tiket'=>$t,'unit'=>self::UNIT]);}
    public function simpanUpload($id){$t=$this->tickets->find((int)$id);$f=$this->request->getFile('dokumen');if(!$t||!$f||!$f->isValid())return redirect()->back()->with('error','Dokumen tidak valid.');$d=WRITEPATH.'uploads/kemahasiswaan';if(!is_dir($d))mkdir($d,0750,true);$n=$f->getRandomName();$f->move($d,$n);$this->tickets->update((int)$id,['result_file'=>$n,'result_note'=>'Dokumen hasil layanan diunggah.']);return redirect()->to(base_url('kemahasiswaan/detail/'.$id))->with('success','Dokumen berhasil diunggah.');}
    public function riwayat(){return $this->dashboard();} public function kirim($id){return $this->updateStatus($id,'completed');} public function kirimKePemohon($id){return $this->updateStatus($id,'completed');} public function hapusDokumen($id){$t=$this->tickets->find((int)$id);if($t&&$t['result_file']){$p=WRITEPATH.'uploads/kemahasiswaan/'.$t['result_file'];if(is_file($p))unlink($p);$this->tickets->update((int)$id,['result_file'=>null,'result_note'=>null]);}return redirect()->back()->with('success','Dokumen dihapus.');}
    public function lihatFile(string $fileName){return $this->serveUploadedFile($fileName,false);} public function downloadFile(string $fileName){return $this->serveUploadedFile($fileName,true);} private function serveUploadedFile(string $fileName,bool $download){$safeFileName=basename($fileName);$filePath=WRITEPATH.'uploads/kemahasiswaan/'.$safeFileName;if(!is_file($filePath))return redirect()->back()->with('error','File hasil layanan tidak ditemukan.');$mimeType=mime_content_type($filePath) ?: 'application/octet-stream';$response=$this->response;$response->setHeader('Content-Type',$mimeType);$response->setHeader('Content-Disposition',($download?'attachment':'inline').'; filename="'.$safeFileName.'"');$response->setBody(file_get_contents($filePath));return $response;}
    private function all():array{return $this->tickets->orderBy('id','DESC')->findAll();} private function label(string $s):string{return ['submitted'=>'Menunggu','processing'=>'Diproses','completed'=>'Selesai','rejected'=>'Ditolak','cancelled'=>'Dibatalkan'][strtolower($s)]??ucfirst($s);} private function decorate(array $t):array{$t['status_tampilan']=$this->label($t['status']??'submitted');$t['nama_layanan']=$t['service_name']??'-';$t['nama_unit']=self::UNIT;$t['nama_pemohon']=$t['applicant_name']??'-';$t['deskripsi']=$t['description']??'-';$t['dokumen_hasil']=!empty($t['result_file'])?[['nama_file'=>$t['result_file'],'nama_asli'=>$t['result_file']]]:[];return $t;} private function updateStatus(int $id,string $s){$t=$this->tickets->find($id);if(!$t)return redirect()->back()->with('error','Tiket tidak ditemukan.');$this->tickets->update($id,['status'=>$s]);$this->log('STATUS_CHANGED','Mengubah status tiket '.$t['ticket_number'],$id,$s);return redirect()->to(base_url('kemahasiswaan/detail/'.$id))->with('success','Status diperbarui.');} private function log(string $action,string $activity,?int $ticketId=null,?string $status=null,?string $note=null): void {db_connect()->table('kemahasiswaan_activity_logs')->insert(['user_id'=>(int)session()->get('user_id')?:null,'ticket_id'=>$ticketId,'action'=>$action,'activity'=>$activity,'status'=>$status,'note'=>$note,'created_at'=>date('Y-m-d H:i:s')]);} private function viewData(array $r):array{$c=['menunggu'=>0,'diproses'=>0,'selesai'=>0,'ditolak'=>0];foreach($r as $t){$x=['submitted'=>'menunggu','processing'=>'diproses','completed'=>'selesai','rejected'=>'ditolak'][$t['status']??'']??null;if($x)$c[$x]++;}return ['title'=>'Dashboard Kemahasiswaan','unit'=>self::UNIT,'tickets'=>$r,'tiket'=>$r,'total'=>count($r),'totalTiket'=>count($r),...$c,'statistikLayanan'=>[],'dataTiketUrl'=>site_url('kemahasiswaan/data-tiket')];}
}
